### PR TITLE
Add a command line tool for device advertising #140

### LINKED ISSUE #140: Add a command line tool for device advertising
What about adding a bluer command line tool for advertising from the command line? The purpose would be to allow users to easily implement wireless solutions such as hobbyists wanting to advertise sensor data from their Raspberry Pi. Current nondeprecated Bluez tools such as bluetoothctl cannot advertise from the command line. 

I have coded a very rough (not correctly formatted idea) at https://github.com/potto216/bluer-cmd/blob/main/le_advertise/src/main.rs

I think besides command line options the program should also be able to read advertising data from a JSON file so the user can write changes in the advertising data from the programing or scripting language of their choice.  

@surban what are your thoughts?

### PR DESCRIPTION
**Pull request by potto216**
Add a command line tool for device advertising. Closes #140

### CODE REVIEW

**Comment by potto216** [comment]
@surban are there any changes I should make?

**Comment by potto216** [comment]
@surban before future commits I'll review the code base for more organized, efficient solutions.
I tested the code and made some minor modifications. In particular I changed the Manufacture Id numeric format from decimal to hexadecimal to match the Bluetooth "Assigned Numbers" document Section "7.1 Company Identifiers by Value" where the Manufacture Ids are in hexadecimal format.

I believe this is ready for the merge, unless you see other issues.

**Comment by surban** [comment]
When `--duration` is specified, shouldn't we exit after the specified time, since the advertisement is removed anyway?

**Comment by surban** [comment]
I don't see anything in the [D-Bus API](https://github.com/bluez/bluez/blob/master/doc/org.bluez.LEAdvertisement.rst) that would provide a notification, when the advertisement is unregistered. I think it is fine to just exit after the specified duration has passed.

**Comment by surban** [comment]
Thanks!

**Pull request merged**
