### PR TITLE
BLE passive scanning

### PR DESCRIPTION
**Pull request by otaviojr**
BLE Passive Scan #27 

Usage:

```
if let Ok(mut monitor_handle) = adapter.register_monitor().await {
    monitor_handle.add_monitor(Monitor {
        activate: Some(Box::new(move || {
            Box::pin(async {
                println!("Monitor 1: Activate funcion called");
                Ok(())
            })
        })),
        release: Some(Box::new(move || {
            Box::pin(async {
                println!("Monitor 1: Release funcion called");
                Ok(())
            })
        })),
        device_found: Some(Box::new(move |device| {
            Box::pin(async move {
                println!("Monitor 1: DeviceFound funcion called: {}",device.addr);
                Ok(())
            })
        })),
        patterns: Some(vec!(Pattern {
            start_position: 2,
            ad_data_type: 0xff,
            content_of_pattern: vec!(190, 172, 57, 237, 152, 255, 41, 0, 68, 26, 128, 47, 156, 57, 143, 193, 153, 210, 0, 1, 0, 100, 197, 100)
        })),
        rssi_low_threshold: Some(127),
        rssi_high_threshold: Some(127),
        rssi_low_timeout: Some(0),
        rssi_high_timeout: Some(0),
        ..Default::default()
    }).await;

    monitor_handle.add_monitor(Monitor {
        activate: Some(Box::new( move || {
            Box::pin(async {
                println!("Monitor 2: Activate funcion called");
                Ok(())
            })
        })),
        release: Some(Box::new( move || {
            Box::pin(async {
                println!("Monitor 2: Release funcion called");
                Ok(())
            })
        })),
        device_found: Some(Box::new(move |device| {
            Box::pin(async move {
                println!("Monitor 2: DeviceFound funcion called: {}",device.addr);
                Ok(())
            })
        })),
        patterns: Some(vec!(Pattern {
            start_position: 2,
            ad_data_type: 0xff,
            content_of_pattern: vec!(190, 172, 57, 237, 152, 255, 41, 0, 68, 26, 128, 47, 156, 57, 143, 193, 153, 210, 0, 1, 0, 100, 197, 100)
        })),
        rssi_low_threshold: Some(127),
        rssi_high_threshold: Some(127),
        rssi_low_timeout: Some(0),
        rssi_high_timeout: Some(0),
        ..Default::default()
    }).await;
}
```

### CODE REVIEW

**Comment by jhartzell42** [comment]
@surban How is this?

**Comment by Taha-Firoz** [comment]
@otaviojr Hows the performance with this, I read somewhere BLE advertisement receival latency is lower because bluez filters don't apply on them. It's the only way to disable duplicate advertisement filter

**Comment by otaviojr** [comment]
> @otaviojr Hows the performance with this, I read somewhere BLE advertisement receival latency is lower because bluez filters don't apply on them. It's the only way to disable duplicate advertisement filter

@Taha-Firoz BLE is part of bluetooth specification and is usually implemented on hardware (I don't get at the bottom of it, maybe someone with more knowledge on this subject could help). So, I believe how it will perform, and how much battery it will save is hardware dependent.

I've been using it with a raspberry pi 4 to open my door for over a year now, and, for my use case, the performance is amazing.

regards,
Otávio Ribeiro

**Comment by jhartzell42** [comment]
@surban how can this be reviewed?

**Comment by surban** [comment]
Thanks for the PR!

I have switched the API from callback based to an event stream to make it consistent with the normal device discovery procedure.

I've merged this PR with my changes but not tested the code. Could you adapt your example to work against the master branch and send me another PR for inclusion of the sample code, i.e. within `bluer/examples/` ?

**Pull request merged**
